apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-fads
  namespace: fraud-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rt-fads
  template:
    metadata:
      labels:
        app: rt-fads
    spec:
      containers:
      - name: rt-fads
        image: rt-fads:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        env:
        - name: MODEL_PATH
          value: "/models/best_model.pt"
        - name: CONFIG_PATH
          value: "/config/production.yaml"
        volumeMounts:
        - name: model-volume
          mountPath: /models
        - name: config-volume
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
      - name: config-volume
        configMap:
          name: rt-fads-config